### ISSUE TITLE
Trashing products

### ISSUE THREAD

**Issue by Janamaria** [UnionDesign/yarn-sites#102]
When we trash a product, could we have it also delete the image in the media file?

**Comment by UnionDesign** [comment]
Wordpress does not work that way but I can add a function to do that. I tested some code because me concern is that this could be dangerous... we don't want to accidentally have some code delete ALL images... or delete images that are being used in more than one place so if you delete product 1 the image also disappears from product 2. But I presume each image is only used in one product. And when I tested all of the above scenarios is seemed safe. So I've promoted the code and worse case, Flywheel does automatic daily backups.
