### ISSUE TITLE
Cart: Duplicate line items (aka cart confusion)

### ISSUE THREAD

**Issue by lizane** [UnionDesign/yarn-sites#107]
So I am in my Cart page, about to check out. It notifies me that Silk Maiden 5759 that I picked out from The Shelf needs to be in a quantity less than or equal to 2, when I then change it to 2 it notifies me I have to pick a quantity less than or equal to 3 but nonetheless won't allow to me proceed with my purchase.
![screen shot 2015-08-10 at 3 23 42 pm](https://cloud.githubusercontent.com/assets/9930894/9179680/726e8ac2-3f74-11e5-9df8-aa4578a98dc5.png)
![screen shot 2015-08-10 at 3 23 50 pm](https://cloud.githubusercontent.com/assets/9930894/9179683/78456b3c-3f74-11e5-87cb-cab08f85b145.png)

**Comment by UnionDesign** [comment]
This is WooCommerce functionality... nothing to do with my code. When I try this it works fine. I get a message at the top of the page saying I have too many in my cart. But you somehow have TWO separate line items with Silk Maiden 5759. Do you know how you did that? I suspect that may have something to do with it. I tried everything and I can only ever get it to show up once on one line. Adding it again just increases the quantity of the one line item I have.

**Comment by lizane** [comment]
Hi David, the Silk Maiden 5759 only showed up on my cart once, those are just two separate screenshots of the same thing to show that the pop up message just changes when i try to change the quantity.

**Comment by lizane** [comment]
david, its the smae line item showing the cart in two states. I think it's becuase it's a shelf product. when you click update cart that piece pops up. When you change it to what it asks for, you get the same message but in reverse. I don't know if ti's just some shelf  products = there is in the cart another shelf product below, but it mgiht be showing just the first error? cameron

**Comment by UnionDesign** [comment]
Ok. I didn't know this was in Chrome. It doesn't so this in Safari. The problem was that some products were picking up a dyed minimum default (i.e. 3) which should not have been picking up any kind of minimum. Combine that with a shelf item that only has 2 in stock and you get impossible logic... a product that can only be order in quantities of 2 or less (because there are only 2 in stock) but must be ordered in a minimum quantity of 3 (because they were accidentally picking up a dyed minimum default). Should be fixed now.
