### ISSUE TITLE
Patterns: URL switches from stage to live

### ISSUE THREAD

**Issue by lizane** [UnionDesign/yarn-sites#112]
When I'm testing the HM public STAGING site, sometimes the link turns into the REGULAR public site and some patterns' related products show Fleece Artist patterns. In the first few minutes when it stays on the staging site, the HM patterns and their related products (HM yarns) look good and are showing up correctly though. http://handmaiden.ca/product/little-square-socks/
![screen shot 2015-08-11 at 9 35 38 am](https://cloud.githubusercontent.com/assets/9930894/9197676/b4104a18-400c-11e5-8c83-773026e77e2f.png)

**Comment by UnionDesign** [comment]
The only question is how did you get to the production site (live) from the staging site. I'm afraid I'm not able to replicate that. I've clicked around quite a bit and I never leave the staging site. What's showing up once your on production isn't really relevant since that "related" thing has been completely replaced with new code.

**Comment by UnionDesign** [comment]
Can't replicate. Assuming it's a non-issue.
