### ISSUE TITLE
Unavailable Products = Free!

### ISSUE THREAD

**Issue by lizane** [UnionDesign/yarn-sites#114]
Small thing, but would it be possible to change the text for unavailable products to "Unavailable" instead of "Free!"? (Please see Merino Sliver in screenshot)
![screen shot 2015-08-11 at 9 47 33 am](https://cloud.githubusercontent.com/assets/9930894/9198062/a293f912-400f-11e5-80e5-68e09c14832c.png)

**Comment by UnionDesign** [comment]
I tested on Safari, Chrome and Firefox on staging and I just see the produce name and the note about it being out of stock. I don't see "Free!". "Free!" isn't even showing up in the source code. So I'm afraid as it stands now I can't replicate this. Maybe it was a WooCommerce bug that was fixed with an update?

**Comment by lizane** [comment]
Double checked it and I think it's fixed!! :D
