### ISSUE TITLE
White yarn images

### ISSUE THREAD

**Issue by Janamaria** [UnionDesign/yarn-sites#98]
When we add an image of a yarn in a colour (as a sample) it usurps the natural yarn image.  Can we keep this natural yarn image as the #1 ranking?

**Comment by UnionDesign** [comment]
This was never part of the design provided... but easily done. Only issue is that natural skeins are uploaded as vertical and we're not generating a small thumbnail version of the rotated (horizontal) skein. But since we're loading the big one anyway (for the slide) I just used it again for the thumbnail.
